name: brg_management
description: A new Flutter project of BRG


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.3

  table_calendar: ^3.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  global_configuration: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  fluttertoast: ^8.0.8
  provider: 6.0.1
  get: 4.1.4
  http: 0.13.5
#  flutter_native_splash: 1.3.3
  flutter_svg: 1.0.1
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.4+4
  qr_flutter: ^4.0.0
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  pinput: ^1.2.0
  local_auth: ^1.1.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  flutter_launcher_icons: "^0.9.2"
  device_info: 2.0.3
  flutter_local_notifications: 9.2.0
  firebase_messaging: 11.2.5
  flutter_app_badger: 1.3.0
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^1.0.6
  flutter_phone_direct_caller: ^2.1.1
  pull_to_refresh: any
  #  for check root jaibreak
  flutter_jailbreak_detection: ^1.8.0
  flutter_secure_storage: ^5.0.2
  share: ^2.0.4
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  open_store: ^0.4.0
  shrink_sidemenu: ^2.0.0+2-null-safety

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  color: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/png/icon_app.png"
  ios_content_mode: scaleAspectFill
  android : true
  android_gravity: fill

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/png/logo.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  fullscreen: false



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/lang/
    - assets/png/
    - assets/svg/
    - assets/jpg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf


